creation_rules:
  - path_regex: \other_config\.bashrc(\.enc)?$
    input_type: binary
    age: 
      - age1pqcgegwjs2uyjmrv5uzqsakfepl99et9fg7hfr845f80z79tx4hsu6a70t
      - age13w8cffzaqkpeea5pzumhhfz78669yuqsxmyjpxck7ef4a0tuye2q6rlecw
      - age145x39h7nzhgd2mx4azjlmyzehsvyulxhv37n0htemqquqm44y3uqwjdafh
      - age1759j2lg97dagglelpug9tws4dcrh4gdhznjnj5yl5r7s0tg50ptqtteduz
